import axios from 'axios';
import React from 'react';

const Statistic = () => {
	const [statistic, setStatistic] = React.useState(null);

	React.useEffect(() => {
		console.log('init');
		const data = {
			fromTime: '2022-04-13T00:00:00.000Z',
			toTime: '2022-04-13T23:59:59.999Z',
			filterTime: [],
			filterDays: [],
			workingHours: [],
			queues: ['Возрождение'],
			columns: [
				'CallTime=dt(inbound_callstates.t)',
				'Address=prop(inbound_callstates,address)',
				'RequestId=prop(inbound_callstates,requestid)',
				'Agents=answeredAgents(inbound_callstates.events)',
				'AgentId=str(inbound_callstates.agentid)',
				'QueueId=str(inbound_callstates.queueid)',
				'Callbacks=checkEvent(inbound_callstates.events,Created CallBack)',
				'Voicemails=checkEvent(inbound_callstates.events,Created VoiceMail)',
				'GreetingsTime=fromToDuration(inbound_callstates.events,Entered in Queue,Connected with Agent;Connected with External;Connected with Internal;Waiting;Ended;Left Queue;Disconnected)',
				'WaitTime=fromToDuration(inbound_callstates.events,Waiting,Connected with Agent;Stop Waiting;Left Queue;Disconnected;Ended;CS_BREAK)',
				'AgentTime=fromToDuration(inbound_callstates.events,Connected with Agent,Disconnected from Agent;Disconnected;Left Queue;Ended)',
				'HoldTime=fromToDuration(inbound_callstates.events,Hold,Unhold;Disconnected from Agent;Disconnected;Left Queue;Ended)',
				'PostprocessingTime=fromToDuration(inbound_callstates.events,Postprocessing,Postprocessing Ended)',
			],
			from: ['inbound_callstates'],
			orderBy: ['CallTime'],
			showColumns: [
				'CallTime',
				'Address',
				'Agents',
				'Callbacks',
				'Voicemails',
				'TotalTime',
				'GreetingsTime',
				'WaitTime',
				'AgentTalkTime',
				'HoldTime',
				'PostprocessingTime',
			],
			dataProcessings: [
				{
					imbueColumns: [
						'TotalTime=sum(GreetingsTime,WaitTime,AgentTime,PostprocessingTime)',
						'AgentTalkTime=substr(AgentTime,HoldTime)',
					],
					groupBy: ['RequestId'],
					filterValues: ['include(QueueId,Возрождение)'],
				},
			],
			dataPostProcessings: [],
			dimensionBasedFields: [
				{
					dimension: 'as_event',
					fields: ['$$$=countEvent(inbound_callstates.events,###)'],
					showColumns: ['$$$'],
				},
			],
			limitRows: 2000,
			translations: {
				columnLabels: {
					CallTime: 'Время',
					Address: 'Телефон',
					Agents: 'Операторы',
					Callbacks: 'Обратные вызовы',
					Voicemails: 'Голосовая почта',
					TotalTime: 'Общее время',
					GreetingsTime: 'Приветствие',
					WaitTime: 'Ожидание',
					AgentTalkTime: 'Время разговора',
					HoldTime: 'Время удержания',
					PostprocessingTime: 'Постобработка',
				},
				columns: ['FailedResult', 'SuccessfulResult'],
				content: {
					'Wait Time (Average on last 100)':
						'Среднее время ожидания 100 последних звонков',
					'Talk Time (Average on last 100)':
						'Среднее время разговора 100 последних звонков',
					'Waiting Count (Max Inbound)':
						'Максимальное количество ожидающих входящих звонков',
					'Unloaded Requests Count': 'Исходящих заявок в БД',
					'Talk Count (Current Inbound)': 'Разговаривает входящих',
					'Talk Count (Current Outbound)': 'Разговаривает исходящих',
					'Listen Count (Current VoiceMail)': 'Прослушивается голосовой почты',
					'Waiting Count (Current Inbound)': 'Ожидает входящих',
					'Online Waiting Count (Current Outbound)': 'Исходящих на линии',
					'Waiting Count (Current Outbound)': 'Ожидает исходящих',
					'Waiting Count (Current VoiceMail)': 'Ожидает голосовой почты',
					'IVR Count (Current Inbound)': 'Входящих на IVR',
					'IVR Count (Current Outbound)': 'Исходящих на IVR',
					'Deferred Count (Current Outbound)': 'Отложено исходящих',
					'Dialing Count (Current Outbound)': 'Дозвон',
					'Idle Time (Current)': 'Ожидание (Текущее)',
					'Alerting Time (Current)': 'Вызов (Текущее)',
					'Talk Time (Current Inbound)': 'На входящем (Текущее)',
					'Talk Time (Current Outbound)': 'На исходящем (Текущее)',
					'Talk Time (Current Internal)': 'На внутреннем (Текущее)',
					'Listen Time (Current VoiceMail)': 'Голосовая почта (Текущее)',
					'Ready Time (Current)': 'Статус Готов (Текущее)',
					'Not Ready Time (Current)': 'Статус Не готов (Текущее)',
					'Wrapup Time (Current)': 'Статус Пауза (Текущее)',
					'Other status Time (Current)': 'Другой статус (Текущее)',
					'Wait Time (Current Average)': 'Среднее время ожидания',
					'Wait Time (Current Max)': 'Наибольшее время ожидания',
					'Service Level (Inbound 5 min)': 'Уровень сервиса за 5 минут',
					'Service Level (Inbound 30 min)': 'Уровень сервиса за 30 минут',
					'Service Level (Inbound 1 hour)': 'Уровень сервиса за последний час',
					'Handling Time (Average)': 'Среднее время обработки',
					'Wait Time to Connect (Inbound Average)': 'Средняя скорость ответа',
					'Wait Time to Connect (Delayed Inbound Average)':
						'Среднee время ожидания ответа',
					'Wait Time to Abandon (Inbound Average)':
						'Среднее время ожидания брошенных звонков',
					'Wait Time to Connect (Outbound Average)': 'Средняя скорость ответа исходящих',
					'Wait Time to Abandon (Outbound Average)':
						'Среднее время ожидания исходящих брошенных звонков',
					'Wait Time (VoiceMail Average)': 'Среднее время ожидания голосовой почты',
					'Work Time': 'Рабочее время',
					'Wrapup Time (Average)': 'Среднее время постобработки',
					'Talk Time (Internal Average)': 'Внутренние, среднее время разговора',
					'Listen Time (Voicemail Average)':
						'Голосовые сообщения, среднее время прослушивания',
					'Idle Time (Average)': 'Ожидание, среднее время',
					'Connected Count (Inbound)': 'Отвечено входящих',
					'Connected Count (Outbound)': 'Отвечено исходящих',
					'Connected Count (Outbound Autoinformer)': 'Обработано автоинформатором',
					'Connected Count (VoiceMail)': 'Обработано голосовой почты',
					'Abandoned Count (Inbound)': 'Брошено входящих',
					'Gave up Count (Inbound)': 'Отменено входящих',
					'VoiceMail Count (Inbound)': 'Оставлено голосовых сообщений',
					'CallBack Count (Inbound)': 'Запрошено обратных звонков',
					'Abandoned Count (Outbound)': 'Брошено исходящих',
					'Dialing Failed Count (Outbound)': 'Не смогли дозвониться',
					'Overwaited Connected Count (Outbound)':
						'Соединенные исходящие, ожидавшие более 5 секунд',
					'Overwaited Abandoned Count (Outbound)':
						'Брошенные исходящие, ожидавшие более 5 секунд',
					'Answered Count (Inbound)': 'Отвечено входящих',
					'Answered Count (Internal)': 'Отвечено внутренних',
					'Answered Count (Outbound)': 'Отвечено исходящих',
					'Answered Count (VoiceMail)': 'Обработано голосовых сообщений',
					'Idle Time': 'Ожидание',
					'Alerting Time': 'Вызов',
					'Talk Time (Inbound)': 'На входящем',
					'Talk Time (Outbound)': 'На исходящем',
					'Talk Time (Internal)': 'На внутреннем',
					'Listen Time (VoiceMail)': 'Голосовая почта',
					'Ready Time': 'Статус Готов',
					'Not Ready Time': 'Статус Не готов',
					'Wrapup Time': 'Статус Пауза',
					'Other status Time': 'Другой статус',
					'Wait Time to Connect (Inbound Maximum)': 'Наибольшее время ожидания ответа',
					'Wait Time to Connect (Outbound Maximum)':
						'Максимальное время ожидания соединения исходящего звонка',
					'Wait Time to Abandon (Inbound Maximum)':
						'Максимальное время ожидания брошенных звонков',
					'Wait Time to Abandon (Outbound Maximum)':
						'Максимальное время ожидания исходящих брошенных звонков',
					'No Free Lines Attempts Count (Outbound)': 'Нет свободных линий',
					'Busy Attempts Count (Outbound)': 'Занято',
					'No Answer Attempts Count (Outbound)': 'Не отвечает',
					'Fax Tone Detected Attempts Count (Outbound)': 'Распознан факс аппарат',
					'Answering Machine Detected Attempts Count (Outbound)':
						'Распознан автоответчик',
					'Human Detected Attempts Count (Outbound)': 'Распознан ответ человека',
					'Flowed out Count': 'Перешли в другую очередь',
					'Flowed in Count': 'Перешли из другой очереди',
					'Idle Time (Maximum)': 'Ожидание (Максимум)',
					'Alerting Time (Maximum)': 'Вызов (Максимум)',
					'Talk Time (Inbound Maximum)': 'На входящем (Максимум)',
					'Talk Time (Outbound Maximum)': 'На исходящем (Максимум)',
					'Talk Time (Internal Maximum)': 'На внутреннем (Максимум)',
					'Listen Time (VoiceMail Maximum)': 'Голосовая почта (Максимум)',
					'Ready Time (Maximum)': 'Статус Готов (Максимум)',
					'Not Ready Time (Maximum)': 'Статус Не готов (Максимум)',
					'Wrapup Time (Maximum)': 'Статус Пауза (Максимум)',
					'Other status Time (Maximum)': 'Другой статус (Максимум)',
					'Idle Count (Global)': 'Ожидание',
					'Alerting Count (Global)': 'Вызов',
					'Talk Count (Global Inbound)': 'На входящем',
					'Talk Count (Global Outbound)': 'На исходящем',
					'Talk Count (Global Internal)': 'На внутреннем',
					'Listen Count (Global VoiceMail)': 'Голосовая почта',
					'Ready Count (Global)': 'Статус Готов',
					'Not Ready Count (Global)': 'Статус Не готов',
					'No Answer Count (Global)': 'Статус Не отвечает',
					'Wrapup Count (Global)': 'Статус Пауза',
					'Other status Count (Global)': 'Другой статус',
					'Total conversation time (PA algorithm)':
						'Общее время разговора (Алгоритм Персональный оператор)',
					'Disconnected By Agent Count': 'Разъединено звонков',
					'Missed Count': 'Пропущено',
					'Alerting Count (More 5 sec)': 'Вызов более 5 сек',
					'Outbound Call Success': 'Успешно',
					'Processed by Outbound IVR': 'Обработан IVR',
					'Outbound Call Abandoned': 'Брошен',
					'Delayed Agent Failed': 'Нет ответа оператора',
					Busy: 'Занято',
					'No Answer': 'Нет ответа абонента',
					'Answering Machine Detected': 'Обнаружен автоответчик',
					Cancelled: 'Вызов отменен оператором',
					Error: 'Ошибка телефонии',
					'Address Error': 'Неверный номер',
					'Unknown Outbound Module Error': 'Неизвестная ошика телефонии',
					'Outbound Dialing Forbidden': 'Вызов запрещён',
					'Outbound Dialing Failure': 'Набор номера невозможен',
					'Detection Abandoned': 'Определение прервано',
					'Temporarily Unavailable': 'Временно недоступен',
					Passes: 'Проходы',
					Total: 'Всего',
					Connected: 'Соединено',
					NotConnected: 'Не соединено',
					Duration: 'Продолжительность',
					AvgDuration: 'Ср. продолжительность',
				},
			},
		};

		axios
			.post('http://192.168.137.102/StatisticsWS/Statistics.svc/getStatistics', data)
			.then(({ data }) => console.log(data));
	}, []);

	return <div>Statistic</div>;
};

export default Statistic;
